# Generated by Django 5.1.2 on 2025-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the landing page', max_length=255)),
                ('subtitle', models.TextField(help_text='Subheading for the landing page')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing_page/')),
                ('about_title', models.CharField(help_text='Title for the About section', max_length=255)),
                ('about_description', models.TextField(help_text='Description for the About section')),
                ('contact_email', models.EmailField(help_text='Contact email displayed on the landing page', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
